### ISSUE TITLE
Getting a "mmap closed or invalid"

### ISSUE THREAD

**Issue by thomasRousseau** [williballenthin/python-evtx#21]
Target file : System.evtx (see the attached zip archive) on a free Win7 VM system (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/)  

Original code :
```
from Evtx.Evtx import Evtx

filename = ...
with Evtx(filename) as evtx_file:
    header = evtx_file.get_file_header()
header.check_magic()

```

Error traceback :
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    header.check_magic()
  File "/home/panda/python-evtx/Evtx/Evtx.py", line 157, in check_magic
    return self.magic() == "ElfFile\x00"
  File "/home/panda/python-evtx/Evtx/BinaryParser.py", line 264, in explicit_length_handler
    return f(offset, length)
  File "/home/panda/python-evtx/Evtx/BinaryParser.py", line 528, in unpack_string
    return self.unpack_binary(offset, length)
  File "/home/panda/python-evtx/Evtx/BinaryParser.py", line 515, in unpack_binary
    return struct.unpack_from("<%ds" % (length), self._buf, o)[0]
ValueError: mmap closed or invalid
```
[System.zip](https://github.com/williballenthin/python-evtx/files/195460/System.zip)

What am I missing ?

**Comment by williballenthin** [comment]
Using `Evtx` as a context manager (that is, like `with Evtx(filename) as evtx_file:`) only keeps the underlying file open in the indented block. Since the parser is lazy, it hasn't actually parsed out all the fields for the header when you assign it to the local variable `header`.  When you try to call `header.check_magic()`, the parser attempts to read from the file to extract the magic header, but its been closed (since the `with` block is done).

The fix is to keep all your code that works with the parsed logfile within the `with` block.

**Comment by thomasRousseau** [comment]
It makes sense ... Thanks !
