### ISSUE TITLE
evtx_dump UnicodeDecodeError with MS DNS log

### ISSUE THREAD

**Issue by stephensheridan** [williballenthin/python-evtx#37]
Hi Will, 

Have updated libraries using pip update and have cloned latest source.

This is the same issue I was having a while back with a MS DNS log file that was generated by my college network admins. This may be a problem with how MS is generating the log file. I have extracted an example of the offending entry (using MS event file viewer) and have attached it here so you can  test against it. NOTE: this does not seem to be an isolated entry in a log file and I have a number of DNS logs that were generated and have the same issues with unicode decoding

The fix for this might be very simple so please excuse my ignorance, maybe there is a nice.

way to handle the UnicodeDecodeError and move on to the next log entry? I'm using evtx_dump in order to generate the plain text XML and extract the DNS query name entries in the log file so I'm not that concerned if I miss a few due to encoding issues.

Thanks for your time

Regards
Stephen
[dns_log_malformed.evtx.zip](https://github.com/williballenthin/python-evtx/files/1035902/dns_log_malformed.evtx.zip)

**Comment by williballenthin** [comment]
Hey @stephensheridan 

Thanks for reporting this issue and taking the time to provide a sample log file. I've been able to reproduce the bug, which you can see [here](https://travis-ci.org/williballenthin/python-evtx/jobs/237347166#L343). I'll trace it down, and update the page here as I make progress.

**Comment by williballenthin** [comment]
As you mentioned,

> You can see the offending characters in the QNAME field. I am not entirely sure why strange characters are appearing, could be a bug in the DNS server log generator or could well be strange encoding error.

[source](https://github.com/williballenthin/python-evtx/issues/28#issuecomment-264921439)

This is indeed this issue. The log declares a region as ASCII text; however, the data in this field is not valid ASCII. I'm not sure how this comes to be, and its probably a bug in the source of the event log entries.

(Technically, the "ASCII string" fields are stored as single byte character (SBC) strings using a specific code page. In practice, this means ASCII most of the time. I suppose its *possible* that the  weird data is actually valid using in some unexpected-but-valid code page. However, even if we knew the code page, cross-platform Python distributions don't include relevant decoders, so we still wouldn't be able to parse the data.)

Do you need to be able to access the data in these records? If its not a critical requirement, then I'll put together some example code showing how to continue processing after encountering invalid records. Otherwise, I'm going to need to put some thought into how to best expose the raw data for you to parse and handle. My gut reaction is that its not appropriate to hard-code in specialized handlers into this library for the DNS log, but perhaps we could explore what this would look like.

**Comment by williballenthin** [comment]
The test case [here](https://github.com/williballenthin/python-evtx/blob/fix/issue-37/tests/test_issue_37.py#L47) demonstrates how to continue processing an evtx file despite encountering an issue decoding corrupt ASCII data.

Fortunately, the issue won't be encountered until you try to parse/render the detailed XML structure of a record. This means you can try/except rendering the XML, and continue on upon error. Fields in the record header, like timestamp and record number, remain accessible; unfortunately, the event ID is stored within the XML structure.

If you must access some fields within this "corrupt" records, let's continue to discuss here. It may be tricky, but I'm confident that we can figure out a solution.


example:
```
    with evtx.Evtx('dns_log_malformed.evtx') as log:
        for chunk in log.chunks():
            for record in chunk.records():
                try:
                    print(record.xml())
                except UnicodeDecodeError:
                    continue
```

**Comment by stephensheridan** [comment]
Hi @williballenthin 

Thank you for the very quick reply and solution. My main point of interest within each event is the QNAME filed. So, I would rather just ignore events that are not properly encoded or have issues. I also think this is an issue with how the DNS evtx log entries are being generated rather than it being a reoccurring case that should be specifically handled in some way by your library.

The code you provided works fine for me and skips over offending events which is exactly what I need to do.

Many thanks
Stephen
