### ISSUE TITLE
Slow performance compared to https://github.com/0xrawsec/golang-evtx

### ISSUE THREAD

**Issue by CaledoniaProject** [williballenthin/python-evtx#87]
I have a 100MB Security.evtx file and it took less than 20s to dump the data with https://github.com/0xrawsec/golang-evtx,

But evtx_dump.py too much longer and didn't finish in 5minutes (I killed it).

**Comment by williballenthin** [comment]
yes, the other project is written in a language that is much more suitable for parsing large amounts of binary data. this python library can parse the files but probably isn't suitable for high performance environments. 

i'd probably suggest that new projects pick the following library instead of python-evtx:

https://github.com/omerbenamram/evtx
